export const REVIEW_COMPONENT =  {
    REVIEWS: {
        LOADING: 'REVIEWS/LOADING',
        LOADED: 'REVIEWS/LOADED',
        ERROR: 'REVIEWS/ERROR'
    },
    REVIEW: {
        CREATING: 'REVIEW/CREATING',
        CREATED: 'REVIEW/CREATED',
        ERROR:'REVIEW/ERROR'
    }
}


